name: CI-CD

on: 
  push: 
    branches: ["main"]
  workflow_dispatch:
    
jobs:
  CI-GREEN:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Criando o arquivo HTML com o green page
        run: sed "s/{{COLOR}}/green/g" ./src/templates/index.html.template > ./src/templates/index.html      

      - name: Construção da imagem Docker do green page
        uses: docker/build-push-action@v3.2.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            fabricioveronez/app-trash:${{ github.run_number }}

  CD-DEV:
    name: CD - Homologação
    runs-on: ubuntu-latest
    needs: [CI-GREEN, ]
    environment: 
      name: homologacao
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
    
      - uses: Azure/k8s-deploy@v5
        with:
          namespace: ${{ secrets.K8S_NAMESPACE }}
          manifests: |
            k8s/deployment.yaml
          images: fabricioveronez/app-trash:${{ github.run_number }}

  CD-PROD:
    name: CD - Produção
    runs-on: ubuntu-latest
    needs: [CI-GREEN, ]
    environment: 
      name: producao
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
    
      - uses: Azure/k8s-deploy@v5
        with:
          namespace: ${{ secrets.K8S_NAMESPACE }}
          manifests: |
            k8s/deployment.yaml
          images: fabricioveronez/app-trash:${{ github.run_number }}