name: CI-CD

on: 
  push: 
    branches: ["main"]
  workflow_dispatch:
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.1.0
      
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      
      - name: Criando o arquivo HTML com o blue page
        run: sed "s/{{COLOR}}/blue/g" ./src/templates/index.html.template > ./src/templates/index.html      

      - name: Construção da imagem Docker do blue page
        uses: docker/build-push-action@v3.2.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            fabricioveronez/web-color:blue
            fabricioveronez/web-page:blue

      - name: Criando o arquivo HTML com o green page
        run: sed "s/{{COLOR}}/green/g" ./src/templates/index.html.template > ./src/templates/index.html      

      - name: Construção da imagem Docker do green page
        uses: docker/build-push-action@v3.2.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            fabricioveronez/web-color:green
            fabricioveronez/web-page:green


    
